Mvc8amAvengersTeam/Controllers/NewController.cs
using Mvc8amAvengersTeam.Filter;
using Mvc8amAvengersTeam.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc8amAvengersTeam.ServiceReference1;
namespace Mvc8amAvengersTeam.Controllers
{



    public class NewController : Controller
    {
        // GET: New usha
        //[NonAction]
        [CustomFilter]
        public ViewResult TestingFiler()
        {
            ViewBag.FavPlayer = "Dhoni";
            return View();
        }

        public string Index()
        {
            return "hello";
        }

        public ActionResult GetMeView()
        {
            string a = Index();
            ViewBag.info = a;
            return View();
        }
        //controller/action/eid
        [Route("student/Arpita")]
        [Route("student/priya")]
        [Route("new/test")]
        public string test(int? id)
        {
            return "My Employee id is " + id + " Name is " + Request.QueryString["name"] + "Designation is " + Request.QueryString["Designation"];
        }

        public ActionResult getSomeData()
        {
            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            ViewBag.empinfo = emp;

            return View();
        }

        public ActionResult getSomeData2()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);

            ViewBag.Emp = listEmployee;


            return View();
        }

        public ActionResult getSomeData3()
        {
            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;
            string a = "asdf";
            String b = "asdfs";

            //object model = emp;
            return View(emp);
        }

        public ActionResult getSomeData4()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);




            return View(listEmployee);
        }

        public ActionResult getSomeData5()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);


            DepartmentModel dept1 = new DepartmentModel();
            dept1.DeptId = 1211;
            dept1.DeptName = "IT";

            DepartmentModel dept2 = new DepartmentModel();
            dept2.DeptId = 1212;
            dept2.DeptName = "Marketing";

            List<DepartmentModel> listDept = new List<Models.DepartmentModel>();
            listDept.Add(dept1);
            listDept.Add(dept2);


            EmpDept ed = new EmpDept();
            ed.emp = listEmployee;
            ed.dept = listDept;


            return View(ed);
        }

        public RedirectResult GetmeSampleView()
        {
            return Redirect("http://www.google.com");
        }

        public RedirectResult GetmeSampleView2()
        {
            return Redirect("~/new/getSomeData5");
        }

        public ActionResult getSomePartialView()
        {
            return View();
        }

        public ActionResult getSomePartialView2()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);

            return View(listEmployee);

        }

        public ActionResult getDirectPv()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);

            return PartialView("_MyEmployeeListPartialView", listEmployee);
        }

        public ActionResult GetMyView()
        {
            return View("getmeView");
        }

        public ActionResult GetMyView2()
        {
            return View("~/Views/Default/Index.cshtml");
        }

        public RedirectToRouteResult GetMyView3()
        {
            return RedirectToAction("Index", "Default", new { id = 1 });
        }

        public RedirectToRouteResult GetMyView4()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);

            return RedirectToAction("Index2", "Default", listEmployee);
        }

        public EmptyResult ExecuteLogic()
        {
            ///logic 
            return new EmptyResult();
        }

        public JsonResult GetjsonData()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);


            DepartmentModel dept1 = new DepartmentModel();
            dept1.DeptId = 1211;
            dept1.DeptName = "IT";

            DepartmentModel dept2 = new DepartmentModel();
            dept2.DeptId = 1212;
            dept2.DeptName = "Marketing";

            List<DepartmentModel> listDept = new List<Models.DepartmentModel>();
            listDept.Add(dept1);
            listDept.Add(dept2);


            EmpDept ed = new EmpDept();
            ed.emp = listEmployee;
            ed.dept = listDept;
            return Json(ed, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetjsonData2()
        {
            List<EmployeeModel> listEmployee = new List<EmployeeModel>();

            EmployeeModel emp = new EmployeeModel();
            emp.EmpId = 1;
            emp.EmpName = "Radha";
            emp.EmpSalary = 700000;

            EmployeeModel emp1 = new EmployeeModel();
            emp1.EmpId = 2;
            emp1.EmpName = "Johny";
            emp1.EmpSalary = 900000;

            EmployeeModel emp2 = new EmployeeModel();
            emp2.EmpId = 3;
            emp2.EmpName = "James";
            emp2.EmpSalary = 600000;

            listEmployee.Add(emp);
            listEmployee.Add(emp1);
            listEmployee.Add(emp2);



            return Json(listEmployee, JsonRequestBehavior.AllowGet);
        }

        public ViewResult GetjsonResultInView()
        {
            return View();
        }

        public FileResult GetFileData()
        {
            return File("~/Web.config", "text");
        }
        public FileResult GetFileData2()
        {

Mvc8amAvengersTeam/Views/New/GetMeView.cshtml
@{
    ViewBag.Title = "GetMeView";
}

<h2>GetMeView</h2>

@DateTime.Now

@ViewBag.info

Mvc8amAvengersTeam/Views/New/GetMyView.cshtml
@{
    ViewBag.Title = "GetMyView";
}

<h2>GetMyView</h2>

Mvc8amAvengersTeam/Views/New/GetjsonResultInView.cshtml
@{
    ViewBag.Title = "GetjsonResultInView";
}

<h2>GetjsonResultInView</h2>

<table id="table1" class="table table-bordered table-hover">
    <tr>
        <th>EmpId</th>
        <th>EmpName</th>
        <th>EmpSalary</th>
    </tr>
</table>

<script src="~/scripts/jquery-1.10.2.min.js"></script>
<script>
    $.ajax({
        url: "http://localhost:53277/new/GetjsonData2",
        type: "Get",
        datatType: "json",
        success: function (result) {
            $.each(result, function (i, key) {
                $('#table1 tr:last').after("<tr><td>" + key.EmpId + "</td><td>" + key.EmpName + "</td><td>" + key.EmpSalary + "</td></tr>")
            })
        }
    })
</script>

Mvc8amAvengersTeam/Views/New/HtmlHelperExample.cshtml
@model Mvc8amAvengersTeam.Models.EmployeeModel
@using Mvc8amAvengersTeam.UserControl
@{
    ViewBag.Title = "HtmlHelperExample";
}

<h2>HtmlHelperExample</h2>

<input type="type" name="name" value="" />
<input type="number" id="FirstName" name="FirstName" value="Sharang" style="background-color:skyblue" class="form-control" onclick="fun()" />
<br />
@Html.TextBox("LastName",null,new { @style = "background-color:gray", @class = "form-control",@type="file", @onclick = "fun()" })
@Html.TextBoxFor(s=>s.EmpName, new { @style = "background-color:gray", @class = "form-control", @onclick = "fun()" })


<input type="file" />

<br />
@Html.Password("pwd","Lion")
<br />
<span>java</span>@Html.CheckBox("java", true)
<span>Dotnet</span>@Html.CheckBox("Dotnet",true)

<br />
<span>Male</span>@Html.RadioButton("Gender","Male",true)
<span>Female</span>@Html.RadioButton("Gender", "Female")

<span>Country</span>
@Html.DropDownList("Country",new List<SelectListItem>() {

new SelectListItem {Text="India",Value="1" },
new SelectListItem {Text="Bangladesh",Value="2",Selected=true },
new SelectListItem {Text="sri lanka",Value="3" }


},"Select Country",new { @class = "form-control" })
<br />
@Html.DropDownList("Movie")<br />
@Html.DropDownList("mvb", (IEnumerable<SelectListItem>)ViewBag.Movie, "Select Movie")
@Html.DropDownListFor(s=>s.EmpName, (IEnumerable<SelectListItem>)ViewBag.Movie, "Select Movie")

@MyUserControl.MyLabel("EmployeeName")
<input type="text" name="name" value="" /><br />
@Html.createUrControl("text")<br />
@Html.createUrControl("checkbox")<br />
@Html.createUrControl("file")<br />
@Html.createUrControl("radio")<br />
@Html.createUrControl("submit")<br />

@helper MySecondLabel(string content)
    {
    <label>@content</label>
    }

@MySecondLabel("I Accept the Agreement")

<script>
    function fun()
    {

        alert('Hello World.....');
    }
</script>

Mvc8amAvengersTeam/Views/New/HtmlHelperExample2.cshtml
@{
    ViewBag.Title = "HtmlHelperExample2";
}

<h2>HtmlHelperExample2</h2>


<form action="~/new/HtmlHelperExample2" method="post">
    <span>UserName</span> @Html.TextBox("UserName")<br />
    <span>Password</span> @Html.Password("Password")<br />
    <span>Gender</span>@Html.RadioButton("Gender", "Male")<span>Male</span> @Html.RadioButton("Gender", "Female")<span>Female</span><br />
    <span>Movie</span>
    @Html.DropDownList("EmployeeName", (IEnumerable<SelectListItem>)ViewBag.Movie, "Select Movie")

    <span>Agreement</span>@Html.CheckBox("Agreement", true)

    <input type="submit" value="Save" />
</form>

Mvc8amAvengersTeam/Views/New/HtmlHelperExample3.cshtml
@model Mvc8amAvengersTeam.Models.RegisterModel

@{
    ViewBag.Title = "HtmlHelperExample3";
}

<h2>HtmlHelperExample3</h2>

@using (Html.BeginForm("HtmlHelperExample3","New",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
        <h4>RegisterModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Gender,"Male", new { htmlAttributes = new { @class = "form-control" } })<span>Male</span>
                @Html.RadioButtonFor(model => model.Gender,"Female", new { htmlAttributes = new { @class = "form-control" } })<span>FeMale</span>
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EmployeeName, (IEnumerable<SelectListItem>)ViewBag.Movie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agreement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Agreement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agreement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mvc8amAvengersTeam/Views/New/TestingFiler.cshtml
@{
    ViewBag.Title = "TestingFiler";
}

<h2>TestingFiler</h2>

@ViewBag.FavPlayer

Mvc8amAvengersTeam/Views/New/ValidationExample.cshtml
@model Mvc8amAvengersTeam.Models.RegisterationFormModel

@{
    ViewBag.Title = "ValidationExample";
}

<h2>ValidationExample</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterationFormModel</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, " ", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, " ", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, " " , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirPassword, " ", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, " ", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, " ", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, " ", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Mvc8amAvengersTeam/Views/New/getSomeData.cshtml
@{
    ViewBag.Title = "getSomeData";
    var emp = ViewBag.empinfo;
}

<h2>getSomeData</h2><br />

@emp.EmpId<br />
@emp.EmpName<br />
@emp.EmpSalary<br />

Mvc8amAvengersTeam/Views/New/getSomeData2.cshtml
@{
    ViewBag.Title = "getSomeData2";
}

<h2>getSomeData2</h2>

<table class="table table-bordered table-striped table-responsive">
    <tr>
        <th>EmpId</th>
        <th>EmpName</th>
        <th>EmpSalary</th>
    </tr>
    @foreach (var item in ViewBag.Emp)
    {
        <tr>
            <td>
                @item.EmpId
            </td>
            <td>
                @item.EmpName
            </td>
            <td>
                @item.EmpSalary
            </td>
        </tr>
    }
</table>

Mvc8amAvengersTeam/Views/New/getSomeData3.cshtml
@model  Mvc8amAvengersTeam.Models.EmployeeModel
@{
    ViewBag.Title = "getSomeData3";
}

<h2>getSomeData3 </h2>


@Model.EmpId<br />
@Model.EmpName<br />
@Model.EmpSalary<br />

Mvc8amAvengersTeam/Views/New/getSomeData4.cshtml
@model  List<Mvc8amAvengersTeam.Models.EmployeeModel>
@{
    ViewBag.Title = "getSomeData4";
}

<h2>getSomeData4</h2>

<table class="table table-bordered table-responsive">
    <tr>
        <th>EmpId</th>
        <th>EmpName</th>
        <th>EmpSalary</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.EmpId</td>
            <td>@item.EmpName</td>
            <td>@item.EmpSalary</td>
        </tr>
    }
</table>

Mvc8amAvengersTeam/Views/New/getSomeData5.cshtml
@model   Mvc8amAvengersTeam.Models.EmpDept
@{
    ViewBag.Title = "getSomeData5";
}

<h2>getSomeData5</h2>

<table class="table table-bordered table-striped">
    <tr>
        <th>EmpId</th>
        <th>EmpName</th>
        <th>EmpSalary</th>
    </tr>
    @foreach (var item in Model.emp)
    {
        <tr>
            <td>@item.EmpId</td>
            <td>@item.EmpName</td>
            <td>@item.EmpSalary</td>
        </tr>
    }
</table>

<table class="table table-bordered table-striped">
    <tr>
        <th>DeptId</th>
        <th>DeptName</th>
    </tr>
    @foreach (var item in Model.dept)
    {
        <tr>
            <td>@item.DeptId</td>
            <td>@item.DeptName</td>
        </tr>
    }
</table>

Mvc8amAvengersTeam/Views/New/getSomePartialView.cshtml
@{
    ViewBag.Title = "getSomePartialView";
}

<h2>getSomePartialView</h2>

<h1>Students Name</h1>
<ul>
    <li>alekhya</li>
    <li>Amol</li>
    <li>Arpita</li>
    <li>chakradhar</li>
    <li>Deepti</li>
</ul>

@Html.Partial("_MyStudentsPartialView")